version: "3"
services:

  worker:
    image: user1/roll20:latest
    deploy:
      mode: replicated
      replicas: 10
      labels: [APP=KILL_THE_GRUE]
      resources:
          limits:
              cpus: "0.1"
              memory: 20M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
